### ISSUE TITLE
一直在不断的下载更新

### ISSUE THREAD

**Issue by tianzhijiexian** [liumenggit/HotWindows#1]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by liumenggit** [comment]
已经修复

**Comment by lingkz** [comment]
一段时间后会失效，要重启脚本

**Comment by lingkz** [comment]
能否放一下源码：）

**Comment by liumenggit** [comment]
去 git下载最新版

    
        
            
                
                    
                        
                    
                    
                        
                            
                            
                            
                                
                                    邮箱：admin@autoahk.com
                                
                        
                    
                
            
        
    
签名由 网易邮箱大师 定制
在2018年05月20日 16:22，ZGP 写道： 能否开源代码

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
{"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/liumenggit/HotWindows/issues/1#issuecomment-390465574","url":"https://github.com/liumenggit/HotWindows/issues/1#issuecomment-390465574","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/liumenggit/HotWindows","title":"liumenggit/HotWindows","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/liumenggit/HotWindows"}},"updates":{"snippets":[{"icon":"PERSON","message":"@zgpio in #1: 能否开源代码"}],"action":{"name":"View Issue","url":"https://github.com/liumenggit/HotWindows/issues/1#issuecomment-390465574"}}}
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "37567f93-e2a7-4e2a-ad37-a9160fc62647",
"title": "Re: [liumenggit/HotWindows] 一直在不断的下载更新 (#1)",
"sections": [
{
"text": "",
"activityTitle": "**ZGP**",
"activityImage": "https://avatars0.githubusercontent.com/u/19503791?s=160\u0026v=4",
"activitySubtitle": "@zgpio",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"liumenggit/HotWindows\",\n\"issueId\": 1,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"liumenggit/HotWindows\",\n\"issueId\": 1\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/liumenggit/HotWindows/issues/1#issuecomment-390465574"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 276854059\n}"
}
],
"themeColor": "26292E"
}
